spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders_service_db
    username: postgres
    password: pass

server:
  port: 8081
