spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: http://localhost:8080
              predicates:
                - Path=/orders/**
              filters:
                - AuthFilter
                - RemoveRequestHeader=Cookie
            - id: security-service
              uri: http://localhost:8090
              predicates:
                - Path=/auth/**
    config:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: api-gateway
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
