spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
    config:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: api-gateway
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/