spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
              filters:
                - AuthFilter
                - name: CircuitBreaker
                  args:
                    id: 1
                    name: ordersCircuitBreaker
                    fallbackUri: forward:/fallback/orders
                - RemoveRequestHeader=Cookie
            - id: security-service
              uri: lb://security-service
              predicates:
                - Path=/auth/**
    config:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: api-gateway
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s