spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders_service_db
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          show_sql: true
          current_session_context_class: thread
          dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092

